changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: New memories
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
